spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dining?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: dining_user
    password: pwd123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        show-sql: true
        format_sql: true
  mustache:
    charset: UTF-8
    servlet:
      expose-request-attributes: true
  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: naver
            client-id: 2pligUpZY6yUNDYdKUa9
            client-secret: L8V2okxSKm
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - email
              - name
              - mobile
              - nickname
          kakao:
            client-name: kakao
            client-id: 05c58cd1257fa2fd7317dde0ff33ddcc
            client-secret: 5ACaQgsaOiKfXdfCJqMW1k4X81lysOfU
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - account_email
              - name
              - phone_number
              - profile_nickname
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
server:
  servlet:
    encoding:
      force-response: true
      charset: UTF-8