spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dining?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: dining_user
    password: pwd123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show-sql: true
        format_sql: true